### ISSUE TITLE
MPESA Integration

### ISSUE THREAD

**Issue by ibnux** [hotspotbilling/phpnuxbill-mpesa#1]
M-Pesa is a mobile banking service that allows users to store and transfer money through their mobile phones. M-Pesa was introduced in Kenya as an alternative way for the population of the country to have access to financial services. Safaricom, the largest mobile phone operator in Kenya, launched M-Pesa in 2007. The service is a blend of two entities where M means mobile and Pesa means money or payment in the Swahili language. 

[Developer Documentation](https://developer.safaricom.co.ke/)

**Comment by faibacon** [comment]
Hi i created login for mpesa. You can use sandbox to test.

**Comment by yusufelias** [comment]
Hi ibnux, kindly share the module

**Comment by yusufelias** [comment]
Hi ibnux, hope you are well. Tried the plugin with 'TransactionType' =>  'CustomerBuyGoodsOnline' however getting a failed transaction error.
